# Generated by Django 3.2.8 on 2021-10-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=20)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=6)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
        ),
    ]
