# Generated by Django 3.2.8 on 2021-10-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20211022_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='map_marker',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
