# Generated by Django 3.2.8 on 2021-10-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomments',
            options={'verbose_name_plural': 'Article Comments'},
        ),
    ]
