# Generated by Django 3.2.8 on 2021-10-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20211030_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontact',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatecoachingcontact',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
