# Generated by Django 3.2.8 on 2021-10-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20211017_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
