# Generated by Django 3.2.8 on 2021-10-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211010_2127'),
        ('checkout', '0004_booking_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
