# Generated by Django 3.2.8 on 2021-10-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_booking_booked_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_course',
            field=models.CharField(max_length=60),
        ),
    ]
