# Generated by Django 3.2.8 on 2021-10-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='available_spaces',
        ),
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_bookings',
        ),
    ]
