# Generated by Django 3.2.8 on 2021-10-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211023_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_complete',
            field=models.BooleanField(default=False),
        ),
    ]
