# Generated by Django 3.2.8 on 2021-10-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_coach_options'),
        ('courses', '0008_course_course_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.coach'),
        ),
    ]
